/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-dm-sans)", "sans-serif"],
        serif: ["var(--font-dm-serif)", "serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Mockup color tokens override map to rescue styling automatically
        slate: {
          50: "#1A1714",
          100: "#1A1714",
          200: "#1A1714",
          300: "#1A1714",
          400: "#7A756F",
          500: "#7A756F",
          600: "#7A756F",
          700: "#7A756F",
          800: "#E6E0D8",
          850: "#E6E0D8",
          900: "#F0EBE3",
          950: "#FFFFFF",
        },
        zinc: {
          50: "#1A1714",
          100: "#1A1714",
          200: "#1A1714",
          300: "#1A1714",
          400: "#7A756F",
          500: "#7A756F",
          600: "#7A756F",
          700: "#7A756F",
          800: "#E6E0D8",
          850: "#E6E0D8",
          900: "#F0EBE3",
          950: "#FFFFFF",
        },
        gray: {
          50: "#1A1714",
          100: "#1A1714",
          200: "#1A1714",
          300: "#1A1714",
          400: "#7A756F",
          500: "#7A756F",
          600: "#7A756F",
          700: "#7A756F",
          800: "#E6E0D8",
          850: "#E6E0D8",
          900: "#F0EBE3",
          950: "#FFFFFF",
        },
        rose: {
          50: "#FBF0EA",
          100: "#EBF2EC",
          200: "#EBF2EC",
          300: "#EBF2EC",
          400: "#2B5730",
          500: "#2B5730",
          600: "#2B5730",
          700: "#2B5730",
          800: "#2B5730",
          900: "#2B5730",
          950: "#EBF2EC",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
}
